'use client';

import {AlertCircle, FileText, RotateCcw} from 'lucide-react';
import type {Employee} from '../lib/agents';
import type {ChatTurn, Classification} from '../lib/chat-types';
import {A2uiSurfaceView, securityConfirmationSurface} from './a2ui-surface';
import {Avatar, AvatarFallback, AvatarImage} from './ui/avatar';
import {AttachmentList} from './attachment-list';
import {ExecutionTrace} from './execution-trace';
import {MarkdownMessage} from './markdown-message';
import {Badge} from './ui/badge';
import {Button} from './ui/button';
import {StatusSpinner} from './ui/status-spinner';

export function MessageThread({employee, turns, onRetry, onConfirmReview, onCancelReview, onClassify}: {
  employee: Employee; turns: ChatTurn[]; onRetry: (message: string) => void; onConfirmReview: (turnId: string) => void; onCancelReview: (turnId: string) => void; onClassify: (turnId: string, artifactId: string, classification: Classification) => void;
}) {
  if (!turns.length) return <div className="mx-auto w-full max-w-[820px] pt-3 sm:pt-8"><section className="grid min-h-[210px] overflow-hidden rounded-lg border sm:grid-cols-[230px_minmax(0,1fr)]" style={{backgroundColor: employee.accentSoft}}><div className="relative min-h-40"><Avatar className="absolute bottom-[-12px] left-1/2 h-[215px] w-[170px] -translate-x-1/2 rounded-none bg-transparent"><AvatarImage className="object-contain object-bottom" src={employee.avatar} alt="" /><AvatarFallback className="rounded-md bg-background/55 text-3xl">{employee.title.slice(0, 1)}</AvatarFallback></Avatar></div><div className="grid content-center gap-4 bg-background/70 p-6 sm:p-8"><div><p className="mb-2 text-[11px] font-bold" style={{color: employee.accent}}>{employee.category} · {employee.version}</p><h1 className="font-serif text-3xl font-semibold sm:text-4xl">{employee.title}</h1></div><p className="max-w-lg text-sm leading-7 text-muted-foreground">{employee.description}</p><div className="flex flex-wrap gap-2"><Badge>成熟度 · {employee.maturity}</Badge>{employee.tags.slice(0, 3).map((tag) => <Badge key={tag}>{tag}</Badge>)}</div></div></section></div>;

  return <div className="mx-auto grid w-full max-w-[820px] gap-8" aria-live="polite">{turns.map((turn) => <article className="grid gap-5" key={turn.id}><div className="flex flex-col items-end gap-2"><div className="max-w-[86%] rounded-lg rounded-br-sm bg-muted px-4 py-2.5 text-sm leading-6 sm:max-w-[72%]">{turn.user}</div>{turn.inputAttachments.length > 0 && <div className="flex max-w-[86%] flex-wrap justify-end gap-1.5 sm:max-w-[72%]">{turn.inputAttachments.map((attachment) => <Badge variant="outline" className="gap-1.5 bg-card" key={attachment.file_path}><FileText size={12} />{attachment.file_name}<span className="text-[9px] text-muted-foreground">{{public: '公开', controlled: '受控', internal: '内部'}[attachment.classification]}</span></Badge>)}</div>}</div><div className="flex min-w-0 items-start gap-2 sm:gap-3"><Avatar className="size-8 sm:size-9" style={{backgroundColor: employee.accentSoft}}><AvatarImage src={employee.avatar} alt="" /><AvatarFallback>{employee.title.slice(0, 1)}</AvatarFallback></Avatar><div className="min-w-0 flex-1 pt-0.5"><span className="mb-2 block text-[10px] text-muted-foreground">{employee.title}</span>{turn.status === 'reviewing' && <div className="flex items-center gap-2 text-xs text-muted-foreground"><StatusSpinner size={15} />安全审查员正在通过 Evo-Harness 检查任务</div>}{turn.status === 'awaiting_confirmation' && turn.review && <A2uiSurfaceView surface={securityConfirmationSurface(turn.review)} onAction={(name) => {if (name === 'confirm_and_continue') onConfirmReview(turn.id); if (name === 'cancel_run') onCancelReview(turn.id);}} />}{turn.status === 'blocked' && <div className="flex items-start gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-destructive"><AlertCircle className="mt-0.5 shrink-0" size={15} /><div><strong className="block">安全审查未通过</strong><span>{turn.review?.summary ?? turn.error}</span></div></div>}<ExecutionTrace turn={turn} />{turn.assistant && <MarkdownMessage>{turn.assistant}</MarkdownMessage>}<AttachmentList items={turn.attachments} onClassify={(artifactId, classification) => onClassify(turn.id, artifactId, classification)} />{!turn.assistant && ['connecting', 'running', 'reconnecting'].includes(turn.status) && <div className="flex items-center gap-2 text-xs text-muted-foreground"><StatusSpinner size={15} />{turn.status === 'reconnecting' ? '连接中断，正在恢复事件流' : '业务员工正在执行任务'}</div>}{turn.status === 'cancel_requested' && <div className="mt-2 text-xs text-amber-700">停止请求已确认，正在等待当前步骤结束</div>}{turn.status === 'cancelled' && <div className="mt-2 text-xs text-amber-700">本轮已停止或已取消</div>}{turn.status === 'failed' && <div className="mt-2 flex items-center gap-2 text-xs text-destructive"><AlertCircle size={15} /><span>{turn.error ?? '执行失败'}</span><Button variant="outline" size="sm" className="h-7 border-red-200 bg-red-50 text-destructive hover:bg-red-100" onClick={() => onRetry(turn.user)}><RotateCcw size={13} />重试</Button></div>}</div></div></article>)}</div>;
}
